Separate server ID from location for controller
hetznercloud/csi-driver pull request #282
Opened 2022-02-23 12:58 UTC by NotTheEvilOne

This PR adds support to execute the CSI controller on a node not hosted on the Hetzner Cloud. Additionally it reduces required API calls in this case as the location is already known at execution.

It adds a new environment variable `HCLOUD_SERVER_OVERRIDE_LOCATION_NAME` used for the controller service to work properly even without a server ID.

This is useful in a Gardener deployment where the "csi-driver-controller" is not necessarily deployed on a node in the Hetzner Cloud offering but still manages volumes for nodes deployed on the cloud.

2022-04-27 11:23 UTC, NotTheEvilOne commented
Is there any news regarding this repository @LKaemmerling or @fhofherr ?

2022-11-14 15:27 UTC, apricote commented
It looks like this location is only used once: https://github.com/hetznercloud/csi-driver/blob/c83b6cc77a7f890a40095cdfd762e001badd602c/driver/controller.go#L57-L63

Considering this, I wonder If we can just completely remove the code, as all volumes should have topology requirements attached by now (GA in Kubernetes since 1.17).

2022-11-15 13:53 UTC, apricote commented
> It looks like this location is only used once:
> 
> https://github.com/hetznercloud/csi-driver/blob/c83b6cc77a7f890a40095cdfd762e001badd602c/driver/controller.go#L57-L63
> 
> Considering this, I wonder If we can just completely remove the code, as all volumes should have topology requirements attached by now (GA in Kubernetes since 1.17).

While this is (IMO) technically allowed according to the CSI spec, the `kubernetes-csi/csi-test` sanity tests fail if we require the accessibilityRequirements to always be set.

I researched how other csi-drivers are doing this, and some also accept config options to override the default location (`digitalocean` and `gce-persistent-disk`).

2022-11-15 13:56 UTC, apricote requested changes

2022-11-15 13:56 UTC, apricote commented on cmd/controller/main.go
> +		server, err := app.GetServer(logger, hcloudClient, metadataClient)
`metadataClient` is only used in this branch. Can you move the `metadataClient := metadata.NewClient()` line here?

2022-11-15 13:56 UTC, apricote commented on cmd/controller/main.go
> +	if s := os.Getenv("HCLOUD_SERVER_OVERRIDE_LOCATION_NAME"); s != "" {
What do you think about calling this var `HCLOUD_VOLUME_DEFAULT_LOCATION` instead?

While this technically provides an override to the server location check, the returned value is used as the default location for volumes which have no location specified.

2023-02-17 12:31 UTC, apricote commented
Hey @NotTheEvilOne, 

I saw that you created 23technologies/hcloud-csi-driver#1 with the requested changes. Should we wait for that PR or just create a new one here with the contents?

2023-02-20 06:35 UTC, NotTheEvilOne commented
Good morning,

I guess we should just go ahead and take over the changes from my [user repository](https://github.com/hetznercloud/csi-driver/compare/main...NotTheEvilOne:hcloud-csi-driver:patch-1). Please let me know if you want me to create a new PR for it.

2023-02-20 09:17 UTC, apricote commented
> Good morning,
> 
> I guess we should just go ahead and take over the changes from my [user repository](https://github.com/hetznercloud/csi-driver/compare/main...NotTheEvilOne:hcloud-csi-driver:patch-1). Please let me know if you want me to create a new PR for it.

That would be great :)

2023-02-20 11:47 UTC, NotTheEvilOne commented
Superseded by #385.

2023-02-20 11:47 UTC, closed without merging

2023-02-20 11:47 UTC, apricote commented
Replaced by #385.