[enhancement] Use native kubernetes topology region label for volumes nodeAffinity
hetznercloud/csi-driver pull request #302
Opened 2022-07-19 15:01 UTC by maksim-paskal

This change helps users that use multiple Hetzner Cloud locations in kubernetes clusters that manage nodes with [Cluster Autoscaler](https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-release-1.23/cluster-autoscaler/cloudprovider/hetzner).

All persistent volumes that are created with this driver has nodeAffinity:
```yaml
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: csi.hetzner.cloud/location
          operator: In
          values:
          - <location>
```

If kubernetes cluster has nodes in multiple Hetzner Cloud location, autoscaler can not detect in which location, new server will be created for pods with such volume specs. Cluster Autoscaler use `topology.kubernetes.io/region` node label to detect in which location new servers are needed.

Signed-off-by: Maksim Paskal <paskal.maksim@gmail.com>

2022-08-03 04:12 UTC, maksim-paskal commented
Hi @LKaemmerling  - please take a look!

2022-11-01 15:33 UTC, maksim-paskal commented
up

2022-11-11 12:38 UTC, apricote commented
@maksim-paskal Thanks for the contribution! I will take a look at this next week.

2022-11-16 12:45 UTC, apricote commented
This took quite a while to research. I will first provide my understanding of the issue you are experiencing, and then list the different options I see to fix it.

### Issue

With our current setup, the following two things are given:

- `hcloud-csi-driver` adds the label `csi.hetzner.cloud/location: <location>` to Node objects (through the `NodeGetInfo` gRPC method)
- Kubernetes adds the this label as a accessibility requirement to every new `PersistentVolume` to make sure that pods are scheduled to the correct nodes.

This breaks for following scenario:

- The cluster is running `cluster-autoscaler` with hetzner cloud provider
- A new pod is created, that references a `PersistentVolumeClaim` with an existing `PersistentVolume`. This pod can not be scheduled because there of missing capacity or incompatible taints on existing nodes.
  - The existing `PV` has the accessibility requirements set as described above
- `cluster-autoscaler` sees the unschedulable pod and tries to find a node group to scale up
  - No node group matches because:
  
    The hetzner cluster-autoscaler provider reports that the new node would have following labels: https://github.com/kubernetes/autoscaler/blob/6be7e801d2ddb8247c99df442495f6eed3d9f9fd/cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go#L316-L322

    ```go
    func buildNodeGroupLabels(n *hetznerNodeGroup) map[string]string {
	    return map[string]string{
		    apiv1.LabelInstanceType:     n.instanceType,
		    apiv1.LabelZoneRegionStable: n.region,
		    nodeGroupLabel:              n.id,
	    }
    }
    ```

    Notably, this list misses the `csi.hetzner.cloud/location` label, which we know the node will also have (if running hcloud-csi-driver). But that label is required so the volume can be scheduled onto the node.
- Because no node group matched the scheduling requirements of the pod, no new node is started and the pod remains unscheduled

In practice, any new node in the right location would actually have the `csi.hetzner.cloud/location` label and match the pods scheduling requirements.

### Solutions

I see three possible solutions with pros and contras for each

- Change the label used in `hcloud-csi-driver`

  This is what this PR suggests. In general I think this would be the cleanest solution, replacing a custom label with a stable standardised label should be done whereever possible.

  **BUT**: The old label will still be used in old `PersistentVolumes`. If now a new node is added to the cluster, our csi-driver would not add the old label, so pods using old  volumes would never be scheduled on new nodes. This would effectivly break the cluster after a while.

  A secondary concern is, that other non-Hetzner Cloud owned tooling might rely on this label existing. But I would be willing to break this compatibility, as we never made any guarantees about this.

- "Soft migrate" the label used in `hcloud-csi-driver`

  Instead of replacing the existing label, we could support both labels. In effect this would mean the following changes:

  - `NodeGetInfo` returns both labels. This means that old PVs containing the deprecated label can still be scheduled to new nodes.
  - As the `CSINode` object now contains both labels, new volume requests also contain both labels as accessibility requirements, we can just read from the new label.
  - On created new Volumes we can change the returned `AccessibleTopology` to only reference the new label. We could also return both labels and kubernetes would match nodes with old and new label, but as all nodes have the new label we can just skip that.

  The only issue I can see here, is that we have to carry two labels until the end of time, as there might always exist old volumes in a cluster.

- Add additional label in new node info in `cluster-autoscaler`. As we know that the label will be set on new nodes, why not tell cluster-autoscaler about this?

  This has the issue, that not all clusters are running the csi-driver. We might provide invalid information to the autoscaler. But a cluster without csi-driver also should never reference the label so :shrug:

2022-11-16 19:30 UTC, maksim-paskal commented
@apricote Thanks for such a detailed explanation of this PR. Appreciated.

I agree that we need some backward compatibility for users that already create PV. “Soft migrate” solution you mention I think is better for the current scenario of usage.

I force commit new changes, with new changes:

1. new nodes will still have label `csi.hetzner.cloud/location`
2. old PV can be mounted on new nodes
3. new PV will have nodeSelectorTerms based on `topology.kubernetes.io/region` 

To use old PV’s with correct autoscaling logic, users must recreate PVC and migrate all data to new PV.  Old label I think we must deprecate in next releases.

Please review my changes.

2022-11-17 14:07 UTC, apricote commented
> To use old PV’s with correct autoscaling logic, users must recreate PVC and migrate all data to new PV.

I think that is fine, as this was never working we dont break any existing deployments.

> Old label I think we must deprecate in next releases.

I don't see a way to remove this value without breaking all old PVs. So while I would deprecate it immediately (as in "mark as deprecated, so no new users start relying on this"), I think we need to keep it for a very long time.

2022-11-17 14:07 UTC, apricote requested changes

2022-11-17 15:25 UTC, maksim-paskal commented on driver/node.go
> +				TopologySegmentLocationLegacy: s.serverLocation,
agree, this topology key is needed for clusters without `hcloud-cloud-controller-manager`

2022-11-17 15:30 UTC, maksim-paskal commented
@apricote  Looks fine for me. Please review my changes.

2022-11-18 07:26 UTC, apricote approved these changes

2022-11-18 07:27 UTC, merged

2022-11-18 07:28 UTC, apricote commented
Thanks for the contribution @maksim-paskal!

I will add a note to the migration guide v1 -> v2 about this autoscaler fix and that existing PVs need to be recreated to work with the autoscaler.

2022-11-25 12:59 UTC, apricote commented
Unfortunatly we had to revert the changes made in this PR as they were non-compliant with the CSI spec and caused issues with Nomad.

I submitted a PR to the `cluster-autoscaler` repo to fix this issue: https://github.com/kubernetes/autoscaler/pull/5322